format = """
$os \
$shell\
$shlvl\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$c\
$dotnet\
$golang\
$java\
$lua\
$nodejs\
$python\
$rust\
$zig\
$jobs\
$fill\
$cmd_duration\n\
$character\
"""

add_newline = false
palette = "catppuccin_mocha"

[os]
disabled = false

[os.symbols]
Arch = " "
Macos = " "
Pop = " "
Ubuntu = " "
Windows = "󰍲 "

[shell]
disabled = false
pwsh_indicator = "_"
style = "bold cyan"

[shlvl]
disabled = false
format = "[$symbol$shlvl ]($style)"
repeat = true
symbol = "❯"
repeat_offset = 1
threshold = 0

[directory]
style = "bold lavender"
truncation_length = 5
truncation_symbol = "…/"

[git_branch]
style = "bold mauve"

[fill]
symbol = " "

[character]
success_symbol = "[[➜](green) ](peach)"
error_symbol = "[[➜](red) ](peach)"
vimcmd_symbol = "[➜ ❮](subtext1)"

# Languages 

[c]
symbol = " "

[dotnet]
symbol = "󰌛 "
format = "via [$symbol($version)]($style)"

[golang]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[rust]
symbol = "󱘗 "

[zig]
symbol = " "

# Palette definitions

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
