format = """
[░▒▓](#a3aed2)\
[ $os ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_state\
$git_status\
[](fg:#394260 bg:#212736)\
$c\
$dotnet\
$golang\
$nodejs\
$python\
$rust\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

add_newline = false

[os]
style = "bg:#a3aed2 fg:#090c0c"
format = "[$symbol]($style)"
disabled = false
symbols = { "Linux" = "",  "Macos" =  "", Windows = "" }

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path]($style)"
use_os_path_sep = false
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = "[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)"

[git_status]
style = "bg:#394260"
format = "[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)"

[c]
symbol = ""
style = "bg:#212736"
format = "[ $symbol ($version $name)]($style)"
version_format = 'v${major}.${minor}'

[dotnet]
symbol = "󰌛"
style = "bg:#212736"
format = "[[ $symbol ($version) - $tfm](fg:#769ff0 bg:#212736)]($style)"
heuristic = false

[golang]
symbol = ""
style = "bg:#212736"
format = "[[ $symbol ($version)](fg:#769ff0 bg:#212736)]($style)"

[nodejs]
symbol = ""
style = "bg:#212736"
format = "[[ $symbol ($version)](fg:#769ff0 bg:#212736)]($style)"

[python]
symbol = ""
style = "bg:#212736"
format = "[[ $symbol ($version)](fg:#769ff0 bg:#212736)]($style)"

[rust]
symbol = ""
style = "bg:#212736"
format = "[[ $symbol ($version)](fg:#769ff0 bg:#212736)]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = "[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
